[tool.poetry]
name = "kr-4"
version = "0.1.0"
description = ""
authors = ["choccocookie <Karanovvlad@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
